// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyfalkapifuntkkbygcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5ZmFsa2FwaWZ1bnRra2J5Z2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTI0MDcsImV4cCI6MjA2Mjg2ODQwN30.8FADwSlDlnCoMe0VElpH835D93N5ZRcePlaTvdjh6lM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);